### PR TITLE
Create a new app

### PR DESCRIPTION
**Pull request by Josphat205**
### In this Branch

- Created a new project
- Initialize your project with Git
- Postgres database set up
- Build  project schema
- Created and run the necessary migration files
- Included Foreign keys

### CODE REVIEW

**Comment by prolajumokeoni** [comment]
Hi @Josphat205, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request
You have submitted a project, that does not have a professional readme,
Kindly use the updated version of the microverse [readme](https://github.com/microverseinc/readme-template) template for your readme 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by prolajumokeoni** [comment]
Hi @Josphat205, Kindly use the updated version of the microverse [readme](https://github.com/microverseinc/readme-template) template for your readme, it was stated in the invalidation above, please add all sections from the microverse readme template, only the FAQ section is optional

**Review by prolajumokeoni — COMMENTED** [review]
Hi @Josphat205 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that does not have the updated microverse readme template , Please add all sections from the microverse readme template, only the FAQ section is optional

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by descholar-ceo — APPROVED** [review]
Hi @Josphat205 🤝 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
👍🏽 Professional PR ✔️ 
👍🏽 Reasme file follow Microverse's updated version ✔️ 
👍🏽 Linters installed and runs without any error ✔️ 
👍🏽 Project is complete and it has all required changes ✔️ 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
